name:                latex-live-snippets
version:             0.1.0.0
github:              "isovector/latex-live-snippets"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2018 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Automatically inline Haskell snippets into LaTeX documents.
category:            System

description:         Please see the README on GitHub at <https://github.com/isovector/latex-live-snippets#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- MissingH
- filepath
- lens

executables:
  latex-live-snippets:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  latex-live-snippets-ghci:
    main:                Main.hs
    source-dirs:         app-ghci
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
